"""Alembic environment.

Connects as the schema owner (riptide_owner) via a sync psycopg driver. The URL
comes from MIGRATION_DATABASE_URL so the same migrations run locally, in CI and
in the compose `migrate` service. No target_metadata: migrations are hand-written
raw SQL, not autogenerated.
"""

import os

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

# Resolve the connection URL from the environment (owner, sync driver).
_url = os.getenv(
    "MIGRATION_DATABASE_URL",
    "postgresql+psycopg://riptide_owner:owner_pw@localhost:5432/riptide",
)
config.set_main_option("sqlalchemy.url", _url)

target_metadata = None  # raw-SQL migrations; autogenerate is not used


def run_migrations_offline() -> None:
    context.configure(
        url=_url,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
